### ISSUE TITLE
led-pixel-mapper implementation

### ISSUE THREAD

**Issue by hallard** [partofthething/infopanel#23]
Hi there,

Really nice work, thanks for sharing.

I think to allow mapper working, in `config.py`, the line in should be uncommented
```python
vol.Optional('led-pixel-mapper', default='') : str,
```
and the trick is in `display.py` were the option name is `pixel_mapper_config` as the example [here](https://github.com/hzeller/rpi-rgb-led-matrix/blob/master/bindings/python/samples/samplebase.py#L55)

```python
# options.led_pixel_mapper = config['led-pixel-mapper']
options.pixel_mapper_config = config['led-pixel-mapper']
```

**Comment by partofthething** [comment]
Thanks! I figured that'd be added to the Python API eventually so I'm glad to hear it has been added now. I will update.

**Comment by partofthething** [comment]
This still does lead to a class of errors on older installs of the RBGmatix library. 

```
Jan 15 08:06:48 tau-over-2 python[1234]: Traceback (most recent call last):
Jan 15 08:06:48 tau-over-2 python[1234]:   File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
Jan 15 08:06:48 tau-over-2 python[1234]:     "__main__", fname, loader, pkg_name)
Jan 15 08:06:48 tau-over-2 python[1234]:   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
Jan 15 08:06:48 tau-over-2 python[1234]:     exec code in run_globals
Jan 15 08:06:48 tau-over-2 python[1234]:   File "/home/pi/infopanel/infopanel/__main__.py", line 5, in <module>
Jan 15 08:06:48 tau-over-2 python[1234]:     driver.run()
Jan 15 08:06:48 tau-over-2 python[1234]:   File "/home/pi/infopanel/infopanel/driver.py", line 250, in run
Jan 15 08:06:48 tau-over-2 python[1234]:     disp = display.display_factory(conf)
Jan 15 08:06:48 tau-over-2 python[1234]:   File "/home/pi/infopanel/infopanel/display.py", line 154, in display_factory
Jan 15 08:06:48 tau-over-2 python[1234]:     options = rgbmatrix_options_factory(config["RGBMatrix"])
Jan 15 08:06:48 tau-over-2 python[1234]:   File "/home/pi/infopanel/infopanel/display.py", line 145, in rgbmatrix_options_factory
Jan 15 08:06:48 tau-over-2 python[1234]:     options.led_pixel_mapper = config['led-pixel-mapper']
Jan 15 08:06:48 tau-over-2 python[1234]: AttributeError: 'rgbmatrix.core.RGBMatrixOptions' object has no attribute 'led_pixel_mapper'
```

**Comment by hallard** [comment]
Correct, 
I tested in the meanwhile but not updated there, here is the fix for `display.py`

```python
    if config["led-pixel-mapper"]:
        options.pixel_mapper_config = config['led-pixel-mapper']
```

**Comment by hallard** [comment]
Just to mention that the current commit does not work, line 
`options.led_pixel_mapper = config['led-pixel-mapper']`
should be 
` options.pixel_mapper_config = config['led-pixel-mapper']`

**Comment by partofthething** [comment]
Thanks for the tip. Sorry about that. Didn't test properly. Just pushed another commit with your suggested change. https://github.com/partofthething/infopanel/commit/7f04aa0f0fca532c5ea1b53d1c6e5dd6fbc36f0d
